# Generated by Django 4.0.3 on 2022-03-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blog_category_blog_categoies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categoies',
            new_name='categories',
        ),
    ]
